repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - --explicit-package-bases
        additional_dependencies:
          - types-requests
          - types-python-dateutil
        files: ^workers/src/workers/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-q", "-r", ".", "-c", "bandit.yml"]
        pass_filenames: false

  # Let pre-commit pass requirements-runtime.txt as the positional file.
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.4.2
    hooks:
      - id: python-safety-dependencies-check
        files: ^requirements-runtime\.txt$
        args: ["--short-report"]
