"""Unit tests for verify_parity_summary.py.

These tests ensure that ``verify_parity_summary`` correctly
interprets parity summary files generated by ``run_parity.py``.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest  # type: ignore

from scripts.verify_parity_summary import verify_parity_summary


def test_verify_parity_summary_success(tmp_path: Path) -> None:
    """verify_parity_summary returns True when marker is present."""
    file = tmp_path / "summary.txt"
    file.write_text("ticker: 2\nuser_update: 2\nSDK parity OK\n")
    assert verify_parity_summary(file) is True


def test_verify_parity_summary_failure(tmp_path: Path) -> None:
    """verify_parity_summary returns False when marker is missing."""
    file = tmp_path / "summary.txt"
    file.write_text("ticker: 1\nuser_update: 2\n")
    assert verify_parity_summary(file) is False