name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Updated to match pyproject.toml

    steps:
      - uses: actions/checkout@v4 # Updated to a current, non-deprecated version

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to a current, non-deprecated version
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all dependencies needed for testing, including those from pyproject.toml
          pip install -r workers/requirements.txt
          pip install slack_bolt aiohttp redis pytest numpy pandas scikit-learn matplotlib alembic
          # Install linting and coverage tools
          pip install ruff coverage bandit safety

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          # Use the correct root 'tests' directory
          coverage run -m pytest -q tests
          coverage xml -o coverage.xml

      - name: Ruff lint and format check
        run: |
          ruff check .
          ruff format --check .

      - name: Security Scan (Bandit & Safety)
        run: |
          bandit -r ./workers/src
          safety check