name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Set up Python environment
        run: |
          poetry env use ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          # Use --no-root to install only dependencies, not the project package itself.
          poetry install --no-root

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest -q tests
          poetry run coverage xml -o coverage.xml

      - name: Lint and Format Check
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: Security Scan (Bandit)
        run: poetry run bandit -r ./workers/src