name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Using a current Python version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming a move to poetry as per pyproject.toml
          pip install poetry
          poetry install

      - name: Set PYTHONPATH
        # This step makes the project root available for imports,
        # resolving ModuleNotFoundError for 'workers', 'scripts', etc.
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          # The test path is also corrected to 'tests/'
          poetry run coverage run -m pytest -q tests
          poetry run coverage xml -o coverage.xml

      - name: Lint and Format Check
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: Security Scan (Bandit)
        run: poetry run bandit -r ./workers/src