name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          pip install poetry
          # Installs all dependencies from pyproject.toml, including ruff
          poetry install --no-root 

      - name: Lint and Format Check with Ruff
        run: poetry run ruff format --check . && poetry run ruff check .

      - name: Run Tests with Coverage
        run: poetry run coverage run -m pytest -q tests