name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install lint group only
        run: poetry install --only lint --no-root

      - name: Run ruff
        run: poetry run ruff check . || true

      - name: Run mypy
        run: poetry run mypy . || true

      - name: Run black
        run: poetry run black --check . || true